[versions]
jansi = "2.4.2"
jline = "3.30.6"
koog = "0.4.1"

[libraries]
jansi = { group = "org.fusesource.jansi", name = "jansi", version.ref = "jansi" }
jline = { group = "org.jline", name = "jline", version.ref = "jline" }
koog = { group = "ai.koog", name = "koog-agents", version.ref = "koog" }
